language: rust
cache: cargo
os: osx
rust: 1.21.0
matrix:
  include:
  - env: TEST_IOS=true RUST_BACKTRACE=1 RUST_TEST_THREADS=1
  - env: RUST_BACKTRACE=1 RUST_TEST_THREADS=1
before_script:
- if [ ! -z "$TEST_IOS" ]; then
    rustup target add i386-apple-ios;
    rustup target add x86_64-apple-ios;
    rustup target add armv7-apple-ios;
    rustup target add armv7s-apple-ios;
    rustup target add aarch64-apple-ios;
  fi
script:
- if [ ! -z "$TEST_IOS" ]; then
      curl -LO https://github.com/azdlowry/rust-test-ios/releases/download/0.1.2/rust-test-ios;
      chmod +x rust-test-ios;
      ./rust-test-ios;
    else
      cargo test;
    fi
