[package]
name = "native-tls"
version = "0.2.6"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
readme = "README.md"

[features]
default = ["security-framework", "security-framework-sys", "lazy_static", "schannel"]
vendored = ["openssl/vendored"]
force-openssl = ["openssl", "openssl-sys", "openssl-probe", "log"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = { version = "2.0.0", optional = true }
security-framework-sys = { version = "2.0.0", optional = true }
lazy_static = { version = "1.4.0", optional = true }
libc = "0.2"
tempfile = "3.1.0"
openssl = { version = "0.10.29", optional = true }
openssl-sys = { version = "0.9.55", optional = true }
openssl-probe = { version = "0.1", optional = true }
log = { version = "0.4.5", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
schannel = { version = "0.1.16", optional = true }
openssl = { version = "0.10.29", optional = true }
openssl-sys = { version = "0.9.55", optional = true }
openssl-probe = { version = "0.1", optional = true }
log = { version = "0.4.5", optional = true }

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
log = "0.4.5"
openssl = "0.10.29"
openssl-sys = "0.9.55"
openssl-probe = "0.1"

[dev-dependencies]
hex = "0.4.2"
