[package]
name = "native-tls"
version = "0.1.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
documentation = "https://docs.rs/native-tls/0.1.1/native_tls"
readme = "README.md"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = { version = "0.1.10", features = ["OSX_10_8"] }
security-framework-sys = "0.1.10"
tempdir = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1.1"

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.9"

[dev-dependencies]
openssl = { version = "0.9", features = ["v102", "v110"] }
