[package]
name = "native-tls"
version = "0.1.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
documentation = "https://docs.rs/native-tls/0.1.2/native_tls"
readme = "README.md"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = { version = "0.1.14", features = ["OSX_10_8" ], git = "https://github.com/sfackler/rust-security-framework.git"}
security-framework-sys = "0.1.14"
tempdir = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1.3"

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
openssl = "0.9.2"
