[package]
name = "native-tls"
version = "0.2.4"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
readme = "README.md"

[features]
vendored = ["openssl/vendored"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = { version = "0.4.4", features = ["alpn"] }
security-framework-sys = "0.4.3"
lazy_static = "1.0"
libc = "0.2"
tempfile = "3.0"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1.16"

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
log = "0.4.5"
openssl = "0.10.29"
openssl-sys = "0.9.55"
openssl-probe = "0.1"

[dev-dependencies]
hex = "0.3"
