version: 2.1

jobs:
  linux:
    parameters:
      image:
        type: string
    docker:
      - image: rust:<< parameters.image >>
    environment:
      RUST_BACKTRACE: 1
      RUSTFLAGS: -D warnings
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: deps-<< parameters.image >>-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - run: rustdoc --test README.md -L target/debug/deps -L target/debug
      - save_cache:
          key: deps-<< parameters.image >>-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
            - target

  macos:
    parameters:
      version:
        type: string
    macos:
      xcode: "10.0.0"
    environment:
      RUST_BACKTRACE: 1
      RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain << parameters.version >>
      - run: ln -s ~/.cargo/bin/* /usr/local/bin
      - restore_cache:
          key: macos-registry
      - run: cargo generate-lockfile
      - save_cache:
          key: macos-registry-{{ .BuildNum }}
          paths:
            - ~/.cargo/registry/index
      - restore_cache:
          key: macos-deps-<< parameters.version >>
      - run: cargo test
      - save_cache:
          key: macos-deps-<< parameters.version >>
          paths:
            - ~/.cargo/registry/cache
            - target

workflows:
  test:
    jobs:
      - linux:
          name: openssl
          image: 1.37.0
      - macos:
          version: 1.37.0
